version: '3.3'

services:
   fvtt:
        container_name: Fvtt
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: fvtt:3.0
        volumes:
          - /data/your/folder/app:/home/foundry/fvtt
          - /data/your/folder/data:/home/foundry/fvttdata
        ports:
            - "30000:30000"
